### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/532-Group21#14]
Hi Group 21,

- cool choice of data and proposed use case!
- 
- There are a lot of grammatical errors in the ‘Research questions you are exploring’ section. 

-  I would like to know more specifically what you mean by ‘fund-sensitive’ countries? I am not quite sure if these are countries where the desired outcomes were seen, or one where they had received funds previously but have not reached the goals yet?
- I really like your dashboard design! Very thorough and looks useful to Alice! 
-It might be useful to display a title with your map and bar graph to show the user which year or data is being displayed.
- check boxes might have to be changed to radial buttons because I think your dashboard in its current iteration can only display one Statistic of interest at a time.
- there are a lot of interactive elements, I’m excited to see which ones you get implemented. Being able to hover over the map and get some info about the country would be helpful since colour ranges can be hard to compare by eye sometimes.

**Comment by eboylestanley** [comment]
All milestone 1 feedback addressed in milestone 2 release.
