### ISSUE TITLE
Group Meeting 1

### ISSUE THREAD

**Issue by chuangw6** [UBC-MDS/532-Group21#2]
## Date&Time: 
15 Jan 2021, 10am - 11am (PST)

## Attendees: 
@chuangw46 @ebs33  @syadk @wangjc640 

## Actionable Items

| ID 	| Assignee 	| Tasks                                                                                                                                                   	| Delivery Time            	|
|----	|----------	|---------------------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------	|
| 1  	| @chuangw46 	| <li>To create two markdown files</li> <li>To push EDA script</li>	| 23:59, 15 Jan 2021 (PST)  	|
| 2  	| @ebs33   	| <li>To refine the prototype</li> <li>To refine the proposal section and research question section</li>                                     	| 23:59, 15 Jan 2021 (PST) 	|
| 3  	| @syadk   	| <li>To write down the description of the sketch</li>    | 23:59, 15 Jan 2021 (PST) 	|
| 4  	| @wangjc640  	| <li>To think about a name for this application</li>  <li>To add a couple of graphs in the EDA script</li>  | 23:59, 15 Jan 2021 (PST) 	|

**Comment by eboylestanley** [comment]
Attached draft mockup

![Draft mockup](https://user-images.githubusercontent.com/63200505/104771144-cdaaa180-573f-11eb-8c63-cb85d19d5bdf.jpg)
