### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/532-Group21#21]
Hi Team 21,

- Well done implementing all design features in your proposal (with a few minor edits/features that need fixing)!!  
The overall functionality and use of the dashboard is easy and intuitive.
- I like that you have a note at the bottom describing what the education ratio means. I’m also wanting to know more about what units population density is in, and maybe a note to direct me to the bottom for descriptions. I did not immediately see the note until I had tried all of the many features you have.
- Using the map works well. I think it would help to have black country outlines for all countries in view on the screen instead of white space because with some of the views it makes it very hard for me to intuitively know what region or sub region I am looking at.
- would be careful with the colour changing on the world map. I realize that each region has different ranges and a changing legend helps see the differences better. However, if I am switching between regions it makes it hard for me to visually do a comparison without remembering values and calculating. 
- I also am actually quite happy with the way you have made the two plots below and I wouldn’t change the order of the bar plot to match the line plot. Having the colour matched is good enough and the ordering from highest to lowest is nice. I know I made this suggestion in your proposal, but seeing the dashboard in action I wouldn't make this change.
- the edits you mentioned in your reflectione to the map section would definitely make that part of the dashboard stronger.

**Comment by eboylestanley** [comment]
Thank you for the feedback!

Feedback tracking can be found here:
https://github.com/UBC-MDS/532-Group21/issues/23
