### ISSUE TITLE
Client feedback

### ISSUE THREAD

**Issue by trevorki** [UBC-MDS/532-Group21#22]
Hello data science team. 
Thank you for your excellent work! I have tried out the app and am pleased with its design and intuitive controls. It does most of what I want it to but I have a few suggestions for improvements:

- It would be nice if the entire app fit on the screen without the need for scrolling down to see the lower plots or to use the controls.
- It can be hard to see countries on the map when they appear outside the frame of the map. I have to use the small scroll bar to locate them. The ability to drag and zoom the plot with the mouse would make it easier.
- When the selection I make contains very few countries the map can be hard to understand because the country is not shown in the context of its region. I’d like to see the outline of the other countries that are not in my selection to help orient myself.
- When I click on a new region, I would like to see the map for the whole region without having to specify a sub-region first. This would allow me to see trends across a wider area.
- Similarly, I would like to be able to see data across all income groups as well, not just the individual groups. 

Thanks,
Alice Bing-Chandler

**Comment by eboylestanley** [comment]
Thank you for the feedback!  

Feedback tracking can be found here:
https://github.com/UBC-MDS/532-Group21/issues/23
